use_frameworks!

platform :ios, '8.0'

target 'ZJJAllModule_Example' do
  pod 'ZJJAllModule', :path => '../'

  target 'ZJJAllModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
